movie_review/movie_review/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("reviews.urls")),
]

movie_review/reviews/urls.py
from django.urls import path
from . import views

urlpatterns = [path("", views.HomePageView.as_view(), name="home")]

movie_review/reviews/models.py
from django.db import models

# Create your models here.
class Review(models.Model):
    title = models.CharField(max_length=100)
    director = models.CharField(max_length=100)
    year = models.PositiveSmallIntegerField()
    actors = models.CharField(max_length=200)
    review = models.TextField()
    # "s" or "ss" is stored is db & 1 o 2 is displayed to the user
    STARS = (
        ("s", 1),
        ("ss", 2),
        ("sss", 3),
        ("ssss", 4),
    )
    # "choices" will show predefined choices to the user i.e STARS
    stars = models.CharField(
        max_length=4,
        choices=STARS,
        default=1,
    )

    def __str__(self):
        return self.title

movie_review/reviews/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Review

# Create your views here.
class HomePageView(ListView):
    model = Review
    template_name = "home.html"

movie_review/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  </head>

  <body>
    <div class="container p-3">
      <h1 class="display-1">Movie Reviews</h1>
      {% block content %} {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>

</html>

movie_review/templates/home.html
{% extends "base.html" %}

{% block content %}
{% for review in review_list %}
    <span class="row text-primary">
      <h3 class="col-4">{{ review.title }}</h3>
      <h3 class="col-8">{% for star in review.stars %}
          &#9733;
        {% endfor %}
      </h3>
    </span>
    <p class="lead">{{ review.review }}</p>
    <p><strong>Starring:</strong> {{ review.actors }}</p>
    <p><strong> by:</strong> {{ review.director }}</p>
    <p class="pb-3"><strong>Year:</strong> {{review.year}}</p>
{% endfor %}
{% endblock content %}